### ISSUE TITLE
Mailbox password is shown under vpn settings

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#11]
**Steps to reproduce**
1. Go to /account
2. Scroll down to password section.

**Current behavior**
Change mailbox password is shown. 

This is a problem because:
1. I'm in vpn settings.
2. The account is vpn only. it's not associated with protonmail address.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63269198-0669f100-c296-11e9-8d77-3e3d335bdb7c.png)

**Comment by mmso** [comment]
Merging this one with https://github.com/ProtonMail/protonvpn-settings/issues/12 since they are because of the same thing
