### ISSUE TITLE
2 password mode is enabled

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#12]
**Summary**
1. Login with vpn only account.
2. Go to /account#passwords
3. Notice how 2 password mode is enabled.

**Current behavior**
2 password mode **is not allowed** in the current web app, but logging into v4 shows that, somehow, 2 password mode is enabled. 😕

**Comment by mmso** [comment]
By default a user with no addresses have 2 password mode enabled. We'll add a check for this case. Thanks @RandomAdversary
