### ISSUE TITLE
Missing favicon 

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#14]
**Summary**
The ProtonVPN favicon is missing.

**Steps to reproduce**
1. Go to any url. ex: /dashboard
2. Notice the favicon.

**Comment by EpokK** [comment]
Use this one: https://account.protonvpn.com/assets/favicon.ico
The `favicon` is loaded from `assets` in `app.ejs`.

**Comment by RandomAdversary** [comment]
@EpokK  That's a good start but, unfortunatelly in 2019, a single favicon is not an option anymore.
We need regular, safari, safari pinned tab, different sizes of the regular icon...
The easiest way would be to get high rez image and generate all the favicons from there.

If you look at the [current website](https://realfavicongenerator.net/favicon_checker?protocol=https&site=account.protonvpn.com) we are already missing lots of icons. I'd like to get this fixed.

**Comment by RandomAdversary** [comment]
fyi: This is how it looks for ProtonMail, I would expect something similar(or better) for ProtonVPN.

![image](https://user-images.githubusercontent.com/11393457/63295337-b0647000-c2cc-11e9-8bc9-143243f085df.png)
