### ISSUE TITLE
Some links are pointing to ProtonMail kb

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#27]
**Summary**
List of links that points to ProtonMail knowledge base. 
Will keep everything in one issue to avoid spam.

**Comment by RandomAdversary** [comment]
- [ ] Learn more link in add credits modal.

**Steps to reproduce**
1. Go to /dashboard
2. Click add credits.
3. Notice the learn more link. 

**Expected behavior**
The link should take me to `https://protonvpn.com/support/vpn-credit-proration/`

**Current behavior**
The link takes me to ProtonMail's knowledge base.

**Comment by RandomAdversary** [comment]
- [ ] Learn more link in payment methods

**Steps to reproduce**
1. Go to /payments#payment-methods
2. Click learn more.

**Expected link**
`https://protonvpn.com/support/payment-options/`

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63278882-679ac000-c2a8-11e9-8642-d6fb58d370e3.png)

**Comment by RandomAdversary** [comment]
- [ ] 2fa link for vpn only users 

**Expected link**
Not sure. At the moment, vpn only users can't have 2fa. 
We can either disable this option, or create new kb article.

@Yobama What do you think?

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63329038-81ccb080-c331-11e9-9f5a-bf68fe045fbe.png)
![image](https://user-images.githubusercontent.com/11393457/63329111-a032ac00-c331-11e9-9996-2a2be2ca9aee.png)

**Comment by Yobama** [comment]
We can leave it like that. VPN apps don't mention 2FA at all, and in dashboard in web-app it's ok to link to ProtonMail KB for 2FA feature.
