### ISSUE TITLE
Clicking on 'JUMP TO' links scrolls to the middle of that section

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/protonvpn-settings#30]
Scenario:

* Scroll all the way down in any of the pages
* Click on any of the 'JUMP TO' links
**Actual result**: page is scrolled to the middle of that section, header is not visible
**Expected result**: page is scrolled to the top of that section and header element is visible

**Comment by EpokK** [comment]
That's a native browser behavior, we are not controlling that.
