### ISSUE TITLE
Reveal password icon can hide parts of the input text.

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#32]
**Summary**
See the attached screenshot. Notice how reveal password icon hides some of the text.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63329533-6e6e1500-c332-11e9-8af9-2cbad2778604.png)
![image](https://user-images.githubusercontent.com/11393457/63329691-b725ce00-c332-11e9-8c87-77c52010efbf.png)

**Comment by nico3333fr** [comment]
Done via https://github.com/ProtonMail/design-system/commit/db68c5fd7f00c234c10f40751ee2703329096769
