### ISSUE TITLE
Increase width for small modal

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#34]
**Summary**
On firefox, the input for credit card expiration year is always truncated.  The user will see only the first 2 numbers of the year, which are useless because every year starts with 20.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63330314-ebe65500-c333-11e9-8464-782626533b4a.png)

**Video**
https://recordit.co/bSTnKHa9mk

**Comment by EpokK** [comment]
I opened an issue for designer to define modal `width` with @nico3333fr

**Comment by nico3333fr** [comment]
Fixed via https://github.com/ProtonMail/design-system/commit/6de3e445f8790bb2c898ab0cc292b339bbeaed57

![image](https://user-images.githubusercontent.com/2578321/63586128-ee011b80-c5a0-11e9-81ef-2bffe04d9d21.png)
