### ISSUE TITLE
Trial users don't have access to all configs

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#35]
**Summary**
Trial period is 7 days and during that time the user can connect to all servers in the app, but they are unable to download the config files from the dashboard.

**Steps to reproduce**
1. Login with user that has active trial period.
2. Try to download config for paid user(ex: secure core, or country config).

**Additional info**
This bug is also present in the current version.

**Comment by vincaslt** [comment]
The logic is the same as in the current Angular application. Trial user is treated as a free user when downloading configs:

```
Tier: PlanName === 'trial' ? 0 : MaxTier
```

We prevent the downloads on the frontend by checking if user has an active vpn subscription: `Subscribed & 4`. In this case - backend returns `Subscribed = 0` when user is on trial, so the check is not passed.

It seems that the access to configs was limited intentionally, but I don't know the reasoning, maybe api guys could chime in on this?

**Comment by bartbutler** [comment]
It's because it's a bad UX when someone configures a device using OpenVPN configs to a premium server and then it just stops working. With the apps we can explain that their trial expired--with the OpenVPN creds it just stops. This was change requested by product.
