### ISSUE TITLE
Unsupported currency & invalid input error when trying to upgrade plan

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#36]
**Steps to reproduce**
1. Login with free user
2. Go to /dashboard#plans
3. Click upgrade on any plan.

**Current behavior**
I'm getting unsupported currency error. Sometimes when changing currencies it shows invalid input.  
Changing to monthly/annually seems to fix the issues.

**Video**
https://recordit.co/3Xxq7F0KMV

**Comment by EpokK** [comment]
I fixed it yesterday.
