### ISSUE TITLE
Free users can download configuration files of Basic pool of servers

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#37]
**Summary**

When Free users use our native application(s) to connect to a ProtonVPN server, we provide them 7 available servers i.e. `US-FREE#1`, `US-FREE#2`, `NL-FREE#1`, `NL-FREE#2`, `JP-FREE#1`, `JP-FREE#2` and `JP-FREE#3`. They don't get to choose to which exact server (basic pool of servers i.e. `US-CA#105`) they will connect to. 

However, at the moment Free users can download the configuration files of each Basic server separately (basic pool of servers used for Free) and then connect to a specific Basic server of their choice via manual OpenVPN/IKEv2 connection (i.e. using OpenVPN GUI on Windows). 
We need to provide them only the 7 configuration files of the free servers. Otherwise, free users can circumvent the whole thing by downloading all configuration files and then connect to a specific Basic server of their choice (i.e. us-ca-105.protonvpn.com) instead of using the configs/hostnames for free.

**Steps to reproduce**
- Log into a Free account
- Navigate to **Downloads**
- Select **Server configs**
- Scroll to the bottom of the page and click **Download all configurations**

**Additional info**
This bug is also present in the current version.

**Comment by vincaslt** [comment]
Will limit that from the frontend, I did not realize the reasoning behind the limitation, so thank you for clarifying that.
Hovewer, frontend limitation does not prevent user from downloading the configurations directly if he knows the url, those limitations should be setup in the backend.
