### ISSUE TITLE
Disabling 2FA: 2 fields are marked as invalid when only 1 is invalid

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/protonvpn-settings#51]
Scenario:

* Login
* Enable 2FA
* Initiate disabling of 2FA
* Enter correct password but incorrect Two-factor code (or the other way around)
* Click 'Submit'

**Actual result**: both fields are marked red as invalid
**Expected result**: only one field with incorrect value is marked as invalid

Also, 'Two-factor code' field validation message says 'Incorrect login credentials. Please try again'. Something like 'Incorrect Two-factor code. Please try again' seems more appropriate.

**Comment by mmso** [comment]
For security reasons we can not differentiate between an incorrect password and an incorrect TOTP code. Closing for that reason.
