### ISSUE TITLE
Cannot add credit card to Payment methods

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/protonvpn-settings#58]
Scenario:

* Login
* Navigate to /payments#payment-methods
* Click 'Add credit card'
* Fill details and click 'Save'

**Result**: nothing happens in the UI, browser console shows error message 'Uncaught (in promise) TypeError: n is not a function'

**Comment by RandomAdversary** [comment]
**Video**
https://recordit.co/auwv2qLTYa
