### ISSUE TITLE
'Invalid gift code' notification is green

### ISSUE THREAD

**Issue by gytiskin** [ProtonMail/protonvpn-settings#59]
Scenario:

* Initiate plan upgrade in /dashboard#plans
* In 'Order summary' modal, enter invalid gift code and click 'Apply'

**Actual result**: green notification with text 'Invalid gift code' appears
**Expected result**: red notification with text 'Invalid gift code' appears

**Comment by RandomAdversary** [comment]
Duplicate of https://github.com/ProtonMail/protonvpn-settings/issues/53
