### ISSUE TITLE
Force plan selection when upgrading subscription

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#66]
**Steps to reproduce**
1. Go to /dashboard
2. Scroll down to Subscription panel.
3. Click upgrade
4. Unselect the current plan
5. Click next

**Expected behavior**
The user shouldn't be able to reach this state.

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/63504063-00138900-c4d1-11e9-8237-d6f5e3498a0f.png)

**Video**
https://recordit.co/BSeQ464yM1

**Comment by EpokK** [comment]
This behavior is not the best UX / UI but OK for now. We are blocking him anyway.
