### ISSUE TITLE
Dropdown button in the pagination can be positioned above the page title

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#69]
**Steps to reproduce**
1. Go to payments
2. Open the dropdown
3. Scroll up

**Screenshots**
![image](https://user-images.githubusercontent.com/11393457/63520096-6fe73b00-c4f4-11e9-819e-bcbd2f89e937.png)
![image](https://user-images.githubusercontent.com/11393457/63520628-509cdd80-c4f5-11e9-8081-bcfbc58d3605.png)

**Comment by EpokK** [comment]
On `scroll`, close dropdown, sounds reasonable for you @mmso @vincaslt ?

**Comment by RandomAdversary** [comment]
I can do the same with closed dropdown.

![image](https://user-images.githubusercontent.com/11393457/63542119-e51c3580-c51f-11e9-86b1-df2e1dc3b89f.png)
