### ISSUE TITLE
Missing error for maximum donation limit

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/protonvpn-settings#73]
**Steps to reproduce**
1. Open donation modal
2. Enter huge donation sum. Ex: 99999999999999999999999999999999999999999 eur.

**Current behavior**
Invalid input error is shown.

**Expected behavior**
![image](https://user-images.githubusercontent.com/11393457/63588790-a3cf6880-c5a7-11e9-9de3-c15b4d8264be.png)

**Comment by EpokK** [comment]
@N4M3Z can we fix that on API side please when we generate the `Token`? For now it's saying `Invalid input`.
